### ISSUE TITLE
I have a problem, he reported an error in Blockchain Explorer, can you help me to see what is wrong with the code?

### ISSUE THREAD

**Issue by solfeng** [The-dLab/LayerZero_NFT_Demo#2]
![image](https://user-images.githubusercontent.com/117896909/201317701-27973234-51a6-4d4a-8c67-6eab3c02a569.png)
![image](https://user-images.githubusercontent.com/117896909/201318087-784cc2c3-926f-4c89-9383-604b264fa64f.png)

**Comment by Thang1usd** [comment]
You are wrong in the precedent part
